### ISSUE TITLE
[Xenoblade X] Anti-Aliasing pack broken, causes strange artifacting +potential fix

### ISSUE THREAD

**Issue by threethan** [cemu-project/cemu_graphic_packs#472]
Here is a snippet of a screenshot of xenoblade x at 1440p with the anti-aliasing graphics pack set to 'Disable Native AA'
![image](https://user-images.githubusercontent.com/12588584/94628626-749d2780-028e-11eb-8c3b-017155b4c3da.png)

The issue here is two-fold. Firstly, there is still some sort of anti aliasing. (Look at the branches of the tree in the background)
Second, and far worse, is enabling the pack, regardless of your settings, causes strange vertical artifacts throughout the screen. (Note the odd scattering of blue pixels around the item diamond and the line next to it. There are also some strange 'cutouts' on my character's arm piece.)

I've tested with OpenGL and Vulkan, both have the same issues.
I only have an AMD gpu, so I don't know if this happens on other platforms. (If you have an Nvidia gpu please test it yourself!)

I do not know what causes this, other than the fact that it _is_ caused by the pack.
I've attached a zip of an alternate version of the pack, which just blanks out the anti-aliasing shader by returning (0,0,0,0).
This doesn't have the options of the original pack, only disabling anti-aliasing, but does actually work.
[AntiAliasingRemover.zip](https://github.com/slashiee/cemu_graphic_packs/files/5302458/AntiAliasingRemover.zip)

**Comment by skalfate** [comment]
I feel like I released a AA pack for this game. But it doesn't go by that name. One of these days I'll catch up and see whats up.

**Comment by Peduls** [comment]
I have a NVIDIA GeForce GTX 1070 and can confirm this issue.

**Comment by threethan** [comment]
Here is an alternate fix - that works with _both_ openGL and vulkan. Put monolib.cpk from this zip over the monolib.cpk in `Xenoblade X > content`
This disables anti-aliasing in the game's internal, not user-accessible graphics config file.
[monolib - no aa.zip](https://github.com/ActualMandM/cemu_graphic_packs/files/5734645/monolib.-.no.aa.zip)

**Comment by intra2** [comment]
Would it be worth it to remove the remove-AA option from the current AA mod and add threethan's graphics pack above labeled as 'Anti-Aliasing Removal' next to the current 'Anti-Aliasing' mod?
