### ISSUE TITLE
[The Legend of Zelda - Twilight Princess HD] Request - Remove Bloom graphics pack

### ISSUE THREAD

**Issue by duke912** [cemu-project/cemu_graphic_packs#508]
Remember playing this game a few years ago (1.12.0 if I remember correctly), and there was a graphics pack to remove bloom from the game, there isn't anymore on the latest cemu versions/graphics packs. Hope you guys can bring it back, since bloom in this game is overkill.

**Comment by skalfate** [comment]
That kind of work I think should be easy for me, however the pack I create may not turn out to be of the latest standard. I feel like I have done work on Zelda's twilight princess bloom before strange...

**Comment by duke912** [comment]
> Hi, posting an update.
> 
> Sorry for the extremely long wait. The pack is finished and will be published soon.

I have even forgotten about this request lol, just replayed the game to see how 'bad' the bloom is, and yes it is really bad, almost make your eyes burn in some areas. Will it be included in the main graphics pack or as a separate download?

**Comment by skalfate** [comment]
Here it is. Try it out and let me know if its to your liking. Thanks.

[TwilightPrincessHD_Bloom.zip](https://github.com/ActualMandM/cemu_graphic_packs/files/7319638/TwilightPrincessHD_Bloom.zip)

**Comment by KoB-Kirito** [comment]
@skalfate You should add that to the packs that get downloaded by cemu. It was pure luck I found this here, and it is essential!
Changing the color to blue is interesting, it basically removes the yellow tint of the default bloom.
Only thing is that you have to restart every time for changes to take effect? At least for me the reload button does nothing.

Here are some previews, maybe it helps someone:

Default for reference:
![cemu 2x 4k 100](https://github.com/user-attachments/assets/9ebc879a-9720-4441-91de-dbf0a3cc2d95)

80%:
![cemu 2x 4k 80](https://github.com/user-attachments/assets/5065e80e-14ea-4198-933e-35c6f809655d)

60%:
![cemu 2x 4k 60](https://github.com/user-attachments/assets/5b3aa855-b3e5-4797-b3ca-edf5de8f7658)

40%:
![cemu 2x 4k 40](https://github.com/user-attachments/assets/c589cb04-b288-419c-8999-44d23f803491)

0% (bloom disabled):
![cemu 2x 4k 0](https://github.com/user-attachments/assets/95e0fe67-86bc-4b3b-91ab-4dc88867ad07)

blue 40%:
![cemu 2x 4k blue 40](https://github.com/user-attachments/assets/78226d6c-4aa5-44fa-a9fe-95b54f32a867)

blue 60%:
![cemu 2x 4k blue 60](https://github.com/user-attachments/assets/210cc7da-2d6b-40ab-873b-3109f83590a0)

blue 80%:
![cemu 2x 4k blue 80](https://github.com/user-attachments/assets/9d4a49c7-efd1-4ae0-bd1a-e85aab2894af)

I can only recommend to play with bloom. The game looks quite dull without any bloom at all.

**Comment by intra0** [comment]
I think this issue has been solved and can be closed right??
current pack by @KoB-Kirito has the option to disable bloom
![image](https://github.com/user-attachments/assets/3c892632-5d3b-477c-a303-ff42da9ed353)

**Comment by skalfate** [comment]
I'll close this issue for now. Thanks to everyone involved.
