### ISSUE TITLE
[Mario Kart 8] When enabling the graphics mod weird line glitches  

### ISSUE THREAD

**Issue by ghost** [cemu-project/cemu_graphic_packs#573]

**Comment by Wavscorn2** [comment]
SOLUTION: Download an older version of graphicsPacks (Link: https://github.com/Crementif/cemu_graphic_packs/releases ) or just google Cemu older graphicspacks or something, and replace the existing folder with it. I personally just used V533. Graphics can be tweaked separately, like Bloom and Resolution in Cemu, unlike the latest ver where everything is in a single folder.

It worked for me, however i just randomly went for V533, if you wanna try a later version you can and test it, i just thought i'd share it in case it helps someone in the future. Annoying glares finally gone

**Comment by Crementif** [comment]
Are you playing on resolutions that aren't 16:9?

**Comment by Wavscorn2** [comment]
Hi Crementif, is your question for me? I'll answer anway, in my experience this issue persists regardless of resolution, ratio, stretched not-stretched, so long as the "graphics" for the game is enabled, just how OltiP2 mentioned.
