### ISSUE TITLE
M & S at the 2016 Olympic games Graphics mod bright screen issue

### ISSUE THREAD

**Issue by Dragonsoul824** [cemu-project/cemu_graphic_packs#605]
For some odd reason when I enable the graphics pack to change resolution, my screen gets all bright. I put 1080p so that it can match my monitor, and put the 60fps patch, but even without any mod enable it still shows white screen, any suggestions.
![Cemu 2 0 (experimental) - FPS_ 62 50  Vulkan   NVIDIA GPU   TitleId_ 00050000-101e5300  Mario   Sonic Rio 2016  US v16  8_22_2023 1_52_02 PM](https://github.com/cemu-project/cemu_graphic_packs/assets/130187907/303f6008-6c89-4667-afe4-7d4d58fe1740)

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	windows 11 64-bit operating system, x64-based processor
GPU   RTX 3070 mobile
using vulken on cemu

**Comment by TheRealWario** [comment]
I believe you have to change the resolution to something higher than your monitor resolution. Try out all the resolutions, and one of them should work
