### ISSUE TITLE
[GAME NAME] Issue

### ISSUE THREAD

**Issue by bnthomason** [cemu-project/cemu_graphic_packs#633]
**Describe the issue**
Xenoblade Chronicles X battle points experience mod blank is blank upon downloading latest graphic packs.

**To Reproduce**
1. Download Cemu latest dev build
2. Download latest graphic pack mod
3. Navigate to mod>experience>battle points.

**Expected behavior**
Options and text visible in the panel

**Screenshots**
![blank](https://github.com/cemu-project/cemu_graphic_packs/assets/68030747/f9073ba7-c0d9-461b-b3b1-bd867cd17ad6)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - GPU: NVIDIA
 - Renderer: Open GL
 - Version: Cemu 2.0.88

**Additional context**
Add any other context about the problem here. **Please provide a save file if it's needed at a specific point in the game.**

**Comment by Exzap** [comment]
This is fixed. See #1307
